import { Injectable, ServiceUnavailableException } from '@nestjs/common';
import { v2 as cloudinary } from 'cloudinary';

/**
 * Signed uploads, not an unsigned upload preset — deliberately, not
 * just the simpler option. An unsigned preset means anyone who ever
 * discovers the preset name (visible in any browser's network tab)
 * could upload arbitrary files to this account indefinitely, consuming
 * storage/bandwidth quota with no way to trace or stop it short of
 * rotating the preset. A signed upload can only be generated by this
 * endpoint, which is admin-guarded — so only an authenticated admin
 * can ever get a valid signature, and each one is time-limited (tied
 * to the timestamp it was issued with).
 *
 * The actual file bytes never pass through this backend at all — the
 * signature just proves to Cloudinary "a real admin authorized this
 * upload," then the browser uploads directly to Cloudinary itself.
 */
@Injectable()
export class UploadsService {
  private configured = false;

  private ensureConfigured() {
    if (this.configured) return;
    const { CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;
    if (!CLOUDINARY_CLOUD_NAME || !CLOUDINARY_API_KEY || !CLOUDINARY_API_SECRET) {
      throw new ServiceUnavailableException(
        'Image upload is not configured yet — set CLOUDINARY_CLOUD_NAME/CLOUDINARY_API_KEY/CLOUDINARY_API_SECRET.',
      );
    }
    cloudinary.config({
      cloud_name: CLOUDINARY_CLOUD_NAME,
      api_key: CLOUDINARY_API_KEY,
      api_secret: CLOUDINARY_API_SECRET,
    });
    this.configured = true;
  }

  getUploadSignature(folder: 'protein-panda/products' | 'protein-panda/reviews' = 'protein-panda/products') {
    this.ensureConfigured();
    const timestamp = Math.round(Date.now() / 1000);
    // folder groups uploads together in the Cloudinary dashboard, and
    // keeps different kinds of uploads separate from each other —
    // restricted to a fixed whitelist (not any caller-supplied string)
    // specifically so a customer-facing caller can never sign a request
    // for the admin-only products folder by just passing a different
    // value.
    const paramsToSign = { timestamp, folder };
    const signature = cloudinary.utils.api_sign_request(paramsToSign, process.env.CLOUDINARY_API_SECRET!);

    return {
      signature,
      timestamp,
      apiKey: process.env.CLOUDINARY_API_KEY,
      cloudName: process.env.CLOUDINARY_CLOUD_NAME,
      folder,
    };
  }
}
