'use client';

import { useEffect, useState } from 'react';

const PAGES = [
  { label: 'Full Nutrition Guide', path: '/nutrition-guide' },
  { label: 'Supplements We Use', path: '/supplements' },
  { label: 'Games & Challenges', path: '/games-info' },
];

export default function QrCodesPage() {
  const [origin, setOrigin] = useState('');

  useEffect(() => {
    setOrigin(window.location.origin);
  }, []);

  return (
    <div>
      <h1 className="mb-2 text-2xl font-extrabold uppercase tracking-tight text-brand-black">QR Codes</h1>
      <p className="mb-6 text-sm text-brand-body">
        Print these on menu cards or table tents so customers can scan straight to the full details, instead of it all being listed out by hand.
      </p>

      {!origin && <p className="text-sm text-brand-body">Loading…</p>}

      <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
        {origin &&
          PAGES.map((p) => {
            const fullUrl = `${origin}${p.path}`;
            const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(fullUrl)}`;
            return (
              <div key={p.path} className="flex flex-col items-center rounded-2xl border border-brand-grey bg-brand-white p-5 text-center">
                <p className="mb-3 text-sm font-bold text-brand-black">{p.label}</p>
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={qrImageUrl} alt={`QR code for ${p.label}`} className="mb-3 h-40 w-40" />
                <p className="mb-3 break-all text-[10px] text-brand-body">{fullUrl}</p>
                <a
                  href={qrImageUrl}
                  download={`${p.path.replace('/', '')}-qr.png`}
                  className="rounded-full bg-brand-black px-4 py-2 text-[10px] font-bold uppercase text-brand-white"
                >
                  Download PNG
                </a>
              </div>
            );
          })}
      </div>

      <p className="mt-6 text-xs text-brand-body">
        QR images are generated by a free third-party service (api.qrserver.com) at print time — nothing about your data is stored there beyond the URL itself, which is already public.
      </p>
    </div>
  );
}
